name: Building and deploying the catalog

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B verify --update-snapshots --file pom.xml
    
    - name: Move catalog jars to public directory
      if: github.ref == 'refs/heads/master' && success() 
      run: |
        mkdir -p public/catalogs
        cp org.eclipse.m2e.discovery.oss/target/*.jar ./public/catalogs

    - name: Deploy to GitHub pages
      if: github.ref == 'refs/heads/master' && success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: true

    - name: Deploy p2 update site
      if: github.ref == 'refs/heads/master' && runner.os == 'Linux'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "2.x"
        title: "m2e catalog"
        files: |
          org.eclipse.m2e.discovery.oss/target/*.jar
          org.eclipse.m2e.discovery.oss/target/classes/directory.xml
